# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VK
  pod 'Alamofire', '~> 5.5'
  pod 'RealmSwift'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

	target 'VKTests' do
	 inherit! :search_paths
	 pod 'Alamofire', '~> 5.5'
  	 pod 'RealmSwift'
  	 pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
	end
end